const I18N = {
  en: {
    'nav.home':'Home','nav.work':'Selected Work','nav.experience':'Experience','nav.credentials':'Credentials','nav.contact':'Contact','nav.cv':'CV ↓',
    'hero.eyebrow':'PROJECT MANAGEMENT · TRANSFORMATION · OPERATIONS','hero.title1':'Turning complex business needs','hero.title2':'into coordinated delivery.','hero.lead':'Project-focused business professional with experience across strategic planning, procurement, commercial delivery, cross-functional coordination and digital transformation — with a critical role in a company-wide custom Odoo ERP program.','hero.cta1':'Explore projects','hero.cta2':"Let's talk ↗",'hero.location':'Saudi Arabia','hero.pmp':'PMI Certified','hero.lss':'Green Belt + Black Belt','hero.card':'Project / Transformation Lead','hero.note1':'ERP ownership','hero.note2':'Cross-functional delivery','hero.note3':'Procurement + commercial','hero.scroll':'Scroll to explore',
    'profile.label':'PROFILE','profile.title':"A project manager's mindset, built through real operating work.",'profile.body':'My experience sits at the intersection of project delivery and business operations. I have worked across business development, procurement, HR, production expansion, supplier coordination and digital systems — often acting as the person connecting stakeholders, requirements, commercial decisions and execution.','profile.body2':'That operating perspective is especially visible in the custom Odoo ERP initiative, where I have been a critical business-side project owner working with consultants and developers to shape a company-wide system around real business needs.',
    'work.kicker':'SELECTED WORK','work.title':'Projects with business consequence.','work.lead':'A selection of initiatives showing ownership, coordination, commercial responsibility and transformation work.',
    'projects.erp.title':'Custom Odoo ERP Transformation','projects.erp.body':"Led the business-side ownership and coordination of a custom Odoo ERP program, working closely with Odoo consultants and developers to translate the company's requirements into a connected system across Finance, Marketing, Purchase, Production, HR, CRM and other business needs.",'projects.erp.side':'Company-wide operating system','projects.factory.title':'Factory Expansion & Setup','projects.factory.body':'Planned, designed and facilitated expansion to a larger production facility, supporting the creation of the ERTQA for Factory sub-brand and coordinating recruitment, machinery and materials sourcing, negotiations, logistics and financials.','projects.factory.side':'Machinery & materials program','projects.webapp.title':'Factory Management WebApp','projects.webapp.body':"Worked with a developer to design a tailored WebApp concept for factory management and production workflows, translating operational requirements into a digital system aligned with the business's actual needs.",'projects.webapp.side':'Custom workflow design','projects.proc.title':'High-Value Procurement & Sourcing','projects.proc.body':'Handled sourcing, supplier negotiations, logistics and financial coordination for machinery and materials, while also managing high-ticket client opportunities with accumulated values up to SAR 700K–1M.','projects.proc.side':'700K–1M accumulated sales values','work.more':'Discuss project ↗',
    'tags.requirements':'Requirements','tags.process':'Process Mapping','tags.stakeholders':'Stakeholders','tags.uat':'UAT / Testing','tags.implementation':'Implementation','tags.facility':'Facility','tags.sourcing':'Sourcing','tags.logistics':'Logistics','tags.finance':'Financial Coordination','tags.businessAnalysis':'Business Analysis','tags.digital':'Digital Workflow','tags.developer':'Developer Collaboration','tags.procurement':'Procurement','tags.negotiation':'Negotiation','tags.suppliers':'Supplier Management','tags.sales':'High-Ticket Sales',
    'metrics.since':'Professional journey starts','metrics.proc':'USD machinery & materials coordinated','metrics.sales':'SAR accumulated high-ticket sales values','metrics.functions':'Core business functions represented in ERP scope',
    'experience.kicker':'EXPERIENCE','experience.title':'A career that crosses functions.','experience.lead':'Each role added another part of the project-delivery picture — from operations and procurement to coordination, recruitment and business development.',
    'roles.current.type':'BUSINESS DEVELOPMENT / PROJECTS','roles.current.title':'Business Development Executive','roles.current.1':'Drive strategic business development by identifying growth opportunities, applying analytical skills, solving challenges and managing special projects with cross-functional teams.','roles.current.2':'Lead procurement to establish cost-efficient supply chains, build client relationships and oversee financial performance to optimize profitability.','roles.current.3':"Act as a critical business-side owner for the company's custom Odoo ERP initiative, coordinating requirements and delivery with consultants and developers across core business functions.",'roles.current.4':'Handle high-ticket sales for VIP clients, luxury brands, government entities and corporates, with accumulated sales values up to SAR 700K–1M.',
    'roles.proc.type':'PROCUREMENT','roles.proc.title':'Procurement Specialist','roles.proc.1':'Analyzed purchasing data to optimize procurement processes and support cost-effective acquisition of goods and services.','roles.proc.2':'Collaborated with internal teams and suppliers to negotiate contracts, monitor performance and meet contract terms.','roles.proc.3':'Used data analysis and cost benchmarking to enhance supply-chain operations and procurement efficiency.',
    'roles.hr.type':'PEOPLE / OPERATIONS','roles.hr.title':'HR Recruitment Coordinator','roles.hr.1':'Sourced and recruited talent to meet expansion requirements and business needs.','roles.hr.2':'Developed tailored recruitment strategies, optimized hiring and interview processes and built relationships with candidates.',
    'roles.pc.type':'PROJECT COORDINATION','roles.pc.title':'Project Coordinator','roles.pc.1':'Planned, executed and oversaw projects to ensure delivery on time, within scope and budget.','roles.pc.2':'Coordinated cross-functional teams across departments for collaboration and communication throughout the project lifecycle.',
    'roles.design.type':'CREATIVE / PRODUCTION','roles.design.title':'Assistant Graphic Designer · Internship','roles.design.1':'Worked with marketing and design teams to create visual materials and support lead designers.',
    'credentials.kicker':'CREDENTIALS','credentials.title':'Certified for structured improvement.','credentials.lead':'Project management discipline backed by PMI, Lean Six Sigma and project-management education, supported by hands-on business experience.','certs.pmp':'Project Management Professional','certs.pmpbody':'PMP certified project-management professional.','certs.lssbrand':'LEAN SIX SIGMA','certs.black':'Black Belt Certified','certs.blackbody':'Advanced process improvement and problem-solving certification.','certs.green':'Green Belt Certified','certs.greenbody':'Process improvement and analytical problem-solving certification.','certs.google':'Project Management Professional Certificate','education.title':'Education','education.acca':'Currently pursuing · 8 exams remaining to ACCA Affiliate Status','languages.title':'Languages','skills.title':'Core skills','skills.lead':'The capabilities most relevant to project, transformation and operations roles.','exhibitions.title':'Industry exposure','exhibitions.body':'Represented the firm locally and overseas in exhibitions and events to scout innovations, network with suppliers and strengthen client relationships.',
    'contact.kicker':'CONTACT','contact.title':'Ready for the next complex project.','contact.body':'Based in Riyadh and open to mid-level project management, transformation, operations and project coordination opportunities.','contact.download':'Download CV ↗','footer':'Project Management · Transformation · Operations'
  },
  ar: {
    'nav.home':'الرئيسية','nav.work':'أبرز المشاريع','nav.experience':'الخبرات','nav.credentials':'المؤهلات','nav.contact':'تواصل','nav.cv':'السيرة الذاتية ↓',
    'hero.eyebrow':'إدارة المشاريع · التحول · العمليات','hero.title1':'تحويل احتياجات الأعمال المعقدة','hero.title2':'إلى تنفيذ منظم ومتكامل.','hero.lead':'محترف يركز على إدارة المشاريع ويتمتع بخبرة في التخطيط الاستراتيجي والمشتريات والتنفيذ التجاري والتنسيق بين الفرق والتحول الرقمي، مع دور محوري في مشروع Odoo ERP مخصص على مستوى الشركة.','hero.cta1':'استعرض المشاريع','hero.cta2':'لنتحدث ↗','hero.location':'المملكة العربية السعودية','hero.pmp':'معتمد من PMI','hero.lss':'الحزام الأخضر + الأسود','hero.card':'قائد مشاريع / تحول','hero.note1':'ملكية مشروع ERP','hero.note2':'تنسيق متعدد الوظائف','hero.note3':'مشتريات + أعمال تجارية','hero.scroll':'مرر للاستكشاف',
    'profile.label':'نبذة','profile.title':'عقلية مدير مشروع، بُنيت من خلال العمل التشغيلي الفعلي.','profile.body':'تقع خبرتي عند تقاطع تنفيذ المشاريع وعمليات الأعمال. عملت في تطوير الأعمال والمشتريات والموارد البشرية وتوسعة الإنتاج والتنسيق مع الموردين والأنظمة الرقمية، وغالبًا كنت حلقة الوصل بين أصحاب المصلحة والمتطلبات والقرارات التجارية والتنفيذ.','profile.body2':'ويتضح ذلك بشكل خاص في مبادرة Odoo ERP المخصصة، حيث أؤدي دورًا محوريًا كمالك للمشروع من جانب الأعمال، بالتعاون مع الاستشاريين والمطورين لبناء نظام شامل وفق الاحتياجات الفعلية للشركة.',
    'work.kicker':'أبرز المشاريع','work.title':'مشاريع ذات أثر مباشر على الأعمال.','work.lead':'مجموعة من المبادرات التي توضح الملكية والتنسيق والمسؤولية التجارية والعمل في التحول المؤسسي.',
    'projects.erp.title':'تحول نظام Odoo ERP المخصص','projects.erp.body':'قيادة الملكية والتنسيق من جانب الأعمال لمشروع Odoo ERP مخصص، والعمل بشكل مباشر مع استشاريي Odoo والمطورين لترجمة احتياجات الشركة إلى نظام مترابط يشمل المالية والتسويق والمشتريات والإنتاج والموارد البشرية وCRM واحتياجات الأعمال الأخرى.','projects.erp.side':'نظام تشغيل على مستوى الشركة','projects.factory.title':'توسعة وتجهيز المصنع','projects.factory.body':'تخطيط وتصميم وتسهيل التوسع إلى منشأة إنتاج أكبر، ودعم إنشاء العلامة الفرعية ERTQA for Factory، مع تنسيق التوظيف وتوريد الآلات والمواد والمفاوضات والخدمات اللوجستية والجانب المالي.','projects.factory.side':'برنامج آلات ومواد','projects.webapp.title':'نظام WebApp لإدارة المصنع','projects.webapp.body':'العمل مع مطور لتصميم مفهوم WebApp مخصص لإدارة المصنع وتدفقات الإنتاج، وترجمة المتطلبات التشغيلية إلى نظام رقمي متوافق مع احتياجات الأعمال الفعلية.','projects.webapp.side':'تصميم سير عمل مخصص','projects.proc.title':'المشتريات والتوريد عالي القيمة','projects.proc.body':'إدارة التوريد والتفاوض مع الموردين والخدمات اللوجستية والتنسيق المالي للآلات والمواد، إلى جانب إدارة فرص مبيعات عالية القيمة بقيم تراكمية تصل إلى 700 ألف–1 مليون ريال سعودي.','projects.proc.side':'قيم مبيعات تراكمية 700 ألف–1 مليون ريال','work.more':'ناقش المشروع ↗',
    'tags.requirements':'المتطلبات','tags.process':'خرائط العمليات','tags.stakeholders':'أصحاب المصلحة','tags.uat':'اختبار / UAT','tags.implementation':'التنفيذ','tags.facility':'المنشأة','tags.sourcing':'التوريد','tags.logistics':'الخدمات اللوجستية','tags.finance':'التنسيق المالي','tags.businessAnalysis':'تحليل الأعمال','tags.digital':'سير العمل الرقمي','tags.developer':'التنسيق مع المطور','tags.procurement':'المشتريات','tags.negotiation':'التفاوض','tags.suppliers':'إدارة الموردين','tags.sales':'مبيعات عالية القيمة',
    'metrics.since':'بداية المسار المهني','metrics.proc':'قيمة برنامج الآلات والمواد بالدولار','metrics.sales':'قيم مبيعات عالية القيمة بالريال','metrics.functions':'وظائف أعمال أساسية ضمن نطاق ERP',
    'experience.kicker':'الخبرات','experience.title':'مسار مهني يعبر عدة وظائف.','experience.lead':'أضاف كل دور جزءًا جديدًا من صورة تنفيذ المشاريع، من العمليات والمشتريات إلى التنسيق والموارد البشرية وتطوير الأعمال.',
    'roles.current.type':'تطوير الأعمال / المشاريع','roles.current.title':'تنفيذي تطوير الأعمال','roles.current.1':'قيادة مبادرات تطوير الأعمال الاستراتيجية من خلال تحديد فرص النمو وتحليل التحديات وإدارة المشاريع الخاصة مع فرق متعددة الوظائف.','roles.current.2':'قيادة المشتريات لبناء سلاسل توريد فعّالة من حيث التكلفة، وبناء علاقات العملاء ومتابعة الأداء المالي لتحسين الربحية.','roles.current.3':'القيام بدور محوري كمالك للمشروع من جانب الأعمال في مبادرة Odoo ERP المخصصة، وتنسيق المتطلبات والتنفيذ مع الاستشاريين والمطورين عبر الوظائف الأساسية.','roles.current.4':'إدارة مبيعات عالية القيمة لعملاء VIP والعلامات الفاخرة والجهات الحكومية والشركات بقيم تراكمية تصل إلى 700 ألف–1 مليون ريال.',
    'roles.proc.type':'المشتريات','roles.proc.title':'أخصائي مشتريات','roles.proc.1':'تحليل بيانات المشتريات لتحسين العمليات ودعم الحصول على السلع والخدمات بتكلفة فعالة.','roles.proc.2':'التعاون مع الفرق الداخلية والموردين للتفاوض على العقود ومتابعة الأداء والالتزام بالشروط.','roles.proc.3':'استخدام تحليل البيانات ومعايير التكلفة لتحسين عمليات سلسلة التوريد وكفاءة المشتريات.',
    'roles.hr.type':'الأفراد / العمليات','roles.hr.title':'منسق توظيف الموارد البشرية','roles.hr.1':'استقطاب وتوظيف المواهب لتلبية متطلبات التوسع واحتياجات الأعمال.','roles.hr.2':'تطوير استراتيجيات توظيف مخصصة وتحسين عمليات المقابلات وبناء العلاقات مع المرشحين.',
    'roles.pc.type':'تنسيق المشاريع','roles.pc.title':'منسق مشاريع','roles.pc.1':'تخطيط وتنفيذ ومتابعة المشاريع لضمان التسليم في الوقت المحدد وضمن النطاق والميزانية.','roles.pc.2':'تنسيق الفرق متعددة الوظائف عبر الإدارات لتعزيز التعاون والتواصل طوال دورة حياة المشروع.',
    'roles.design.type':'الإبداع / الإنتاج','roles.design.title':'مساعد مصمم جرافيك · تدريب','roles.design.1':'العمل مع فرق التسويق والتصميم لإنتاج المواد البصرية ودعم المصممين الرئيسيين.',
    'credentials.kicker':'المؤهلات','credentials.title':'اعتمادات تدعم التحسين المنهجي.','credentials.lead':'انضباط في إدارة المشاريع مدعوم باعتمادات PMI وLean Six Sigma وتعليم في إدارة المشاريع، إلى جانب خبرة عملية في الأعمال.','certs.pmp':'محترف إدارة المشاريع','certs.pmpbody':'محترف إدارة مشاريع حاصل على اعتماد PMP.','certs.lssbrand':'LEAN SIX SIGMA','certs.black':'حزام أسود معتمد','certs.blackbody':'اعتماد متقدم في تحسين العمليات وحل المشكلات.','certs.green':'حزام أخضر معتمد','certs.greenbody':'اعتماد في تحسين العمليات والتحليل وحل المشكلات.','certs.google':'الشهادة المهنية في إدارة المشاريع','education.title':'التعليم','education.acca':'يواصل الدراسة · 8 اختبارات متبقية للوصول إلى حالة Affiliate في ACCA','languages.title':'اللغات','skills.title':'المهارات الأساسية','skills.lead':'أهم القدرات المرتبطة بأدوار إدارة المشاريع والتحول والعمليات.','exhibitions.title':'التعرض للقطاع','exhibitions.body':'تمثيل الشركة محليًا ودوليًا في المعارض والفعاليات لاستكشاف الابتكارات وبناء شبكة الموردين وتعزيز علاقات العملاء.',
    'contact.kicker':'تواصل','contact.title':'جاهز للمشروع المعقد القادم.','contact.body':'مقيم في الرياض ومنفتح على فرص إدارة المشاريع والتحول والعمليات وتنسيق المشاريع على المستوى المتوسط.','contact.download':'تحميل السيرة الذاتية ↗','footer':'إدارة المشاريع · التحول · العمليات'
  }
};

let lang = localStorage.getItem('za-lang') || 'en';
let theme = localStorage.getItem('za-theme') || (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
const html = document.documentElement;
const body = document.body;
const themeIcon = document.getElementById('themeIcon');
function applyTheme(){html.dataset.theme=theme==='dark'?'dark':''; themeIcon.textContent=theme==='dark'?'☀':'☾'; localStorage.setItem('za-theme',theme)}
function applyLang(){const pack=I18N[lang]; html.lang=lang; html.dir=lang==='ar'?'rtl':'ltr'; body.classList.toggle('rtl',lang==='ar'); document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(pack[k])el.textContent=pack[k]}); document.getElementById('langBtn').textContent=lang==='en'?'ع':'EN'; localStorage.setItem('za-lang',lang)}
applyTheme();applyLang();
document.getElementById('themeBtn').addEventListener('click',()=>{theme=theme==='dark'?'light':'dark';applyTheme()});
document.getElementById('langBtn').addEventListener('click',()=>{lang=lang==='en'?'ar':'en';applyLang()});

const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.12,rootMargin:'0px 0px -40px'}); document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
const navSections=['home','work','experience','credentials','contact'];
const navObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){document.querySelectorAll('.desktop-nav a').forEach(a=>a.classList.toggle('active',a.dataset.nav===e.target.id))}}),{rootMargin:'-35% 0px -55% 0px',threshold:0});navSections.forEach(id=>{const el=document.getElementById(id);if(el)navObserver.observe(el)});

document.querySelectorAll('.magnetic').forEach(btn=>{btn.addEventListener('pointermove',e=>{if(innerWidth<700)return;const r=btn.getBoundingClientRect();const x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;btn.style.transform=`translate(${x*.12}px,${y*.12}px) scale(1.03)`});btn.addEventListener('pointerleave',()=>btn.style.transform='')});
const cursor=document.getElementById('cursorDot');window.addEventListener('pointermove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px';cursor.style.opacity=innerWidth>900?'1':'0'},{passive:true});document.querySelectorAll('a,button,.project-card,.credential-card').forEach(el=>{el.addEventListener('mouseenter',()=>{cursor.style.width='30px';cursor.style.height='30px';cursor.style.background='rgba(139,209,188,.12)'});el.addEventListener('mouseleave',()=>{cursor.style.width='12px';cursor.style.height='12px';cursor.style.background='transparent'})});
const tilt=document.getElementById('tiltCard');document.getElementById('heroVisual').addEventListener('pointermove',e=>{if(innerWidth<900)return;const r=tilt.parentElement.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;tilt.style.transform=`rotate(${5+x*-5}deg) rotateX(${y*-5}deg) rotateY(${x*7}deg) translateY(-4px)`});document.getElementById('heroVisual').addEventListener('pointerleave',()=>tilt.style.transform='rotate(5deg)');
window.addEventListener('scroll',()=>{const y=scrollY;document.getElementById('topbar').style.transform=`translateX(-50%) translateY(${Math.min(y*.015,7)}px)`},{passive:true});
